### ISSUE TITLE
Core: Replace dbus with dbus-broker

### ISSUE THREAD

**Issue by travier-anssi** [clipos/bugs#13]
See https://github.com/bus1/dbus-broker/wiki

- [x] Update upstream Gentoo ebuild to the latest stable version
- [x] Replace dbus with dbus-broker

**Comment by withdark** [comment]
Hello,
The version of dbus-broker is now in 21 but not mainline on gentoo, should we start with 18 (mainline on gentoo) and then make a future patch?

**Comment by travier-anssi** [comment]
I think it would be best to first push the latest stable version upstream in Gentoo and then use it in CLIP OS.

**Comment by travier-anssi** [comment]
This is done as of:
* https://github.com/clipos/products_clipos/commit/8a13154530f0bae00b3fed1e220e8c6673a6c045
* https://github.com/clipos/src_portage_clipos/commit/5e14cdc8610d1849154accfc35296cf8d78e1749
