### ISSUE TITLE
Core: Add more Linux hardening

### ISSUE THREAD

**Issue by theLOICofFRANCE** [clipos/bugs#18]
Good morning, everyone,

I think it would be interesting to add the following hardenings:

1. [Symlinkown](https://github.com/hannob/symlinkown)
2. [S.A.R.A](https://github.com/smeso/sara/releases)
3. [TPE-LSM](https://lkml.org/lkml/2017/6/7/1415) or [TPE-without-LSM](https://github.com/HacKurx/public-sharing/blob/master/TPE-without-LSM.patch)
4. [Hardened defconfig](https://patchwork.kernel.org/patch/10593391/)
5. [Vmware PAX, PAX_NOWRITEEXEC, PAX_EMUTRAMP, PAX_MPROTECT](https://github.com/vmware/photon/blob/master/SPECS/linux/0001-NOWRITEEXEC-and-PAX-features-MPROTECT-EMUTRAMP.patch)
6. [Vmware PAX_RANDKSTACK](https://github.com/vmware/photon/blob/master/SPECS/linux/0002-Added-PAX_RANDKSTACK.patch)
7. [Vmware rap_plugin](https://github.com/vmware/photon/blob/master/SPECS/linux/0003-Added-rap_plugin.patch) can be used with a [gcc patch](https://github.com/vmware/photon/blob/master/PUBLISHRPMS_SPECS/gcc/PLUGIN_TYPE_CAST.patch).

There is no difficulty to maintain on the longterm version of linux 4.19.

Best regards,

**Comment by tsautereau-anssi** [comment]
This issue was moved to https://discuss.clip-os.org/t/core-add-more-linux-hardening/30
