### ISSUE TITLE
Ubuntu 18.04: source toolkit/source_me.sh fails with 'no matching package named `executable-path` found'

### ISSUE THREAD

**Issue by shauser** [clipos/bugs#2]
Running `toolkit/source_me.sh` returns the following error while installing just on Ubuntu 18.04.1. Installing executable-path manually didn't solve the issue for some reason.

```
Installing collected packages: cosmk
  Found existing installation: cosmk 0.1.0
    Uninstalling cosmk-0.1.0:
      Successfully uninstalled cosmk-0.1.0
  Running setup.py develop for cosmk
Successfully installed cosmk
  Installing just v0.3.12
error: failed to compile `just v0.3.12`, intermediate artifacts can be found at `/media/clipos/run/cargo/target`

Caused by:
  no matching package named `executable-path` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `just v0.3.12`
```

## Specifications

- Version: n/a
- Platform: Ubuntu 18.04.1
- Subsystem: toolkit

**Comment by cyrinux** [comment]
Hi @shauser, do you really "source" this file?

`source toolkit/source_me.sh`

**Comment by shauser** [comment]
Yes, sorry, that was not clear above:

```
$ source toolkit/source_me.sh 
 [*] Setting up a "toolkit" virtualenv...
     Please be patient as this may take some time on the first run.
 [!] Virtualenv setup has failed.
     Please read the log in "run/virtualenv_setup.log" at repo root level.
```

**Comment by cyrinux** [comment]
Ok, so you progress? Or this is a new error now?

**Comment by travier-anssi** [comment]
Hi! Thanks for the report. This is a known issue with the version of cargo (part of Rust) packaged in Ubuntu 18.04. Please install the latest stable version of Rust using https://rustup.rs for now. We will add a workaround soon.
