### ISSUE TITLE
Bootstrap :: systemd, git: command not found

### ISSUE THREAD

**Issue by ostree** [clipos/bugs#21]
## Expected Behavior

A correct botstrap

## Actual Behavior

Unpacking source...
/var/tmp/portage/sys-apps/systemd-238-r100/temp/environment: line 1500: git: command not found
ERROR: sys-apps/systemd-238-r100::clipos failed (unpack phase):
Can't clone /mnt/src/external/systemd.

## Steps to Reproduce the Problem

1. source toolkit/source_me.sh
2. (toolkit) $ cp toolkit/instrumentation.toml.example instrumentation.toml
3. sujust all

## Specifications

- Version: sys-apps/systemd-238-r100
- Platform: Linux
- Subsystem: Debian

**Comment by ostree** [comment]
I've told portage to install git too and before systemd

**Comment by ngodinho-anssi** [comment]
Hi! Thanks for the report. The fix was awaiting validation on our [Gerrit](https://review.clip-os.org/c/clipos/src_portage_clipos/+/2491) instance. The commit should arrive soon in the tree.
