### ISSUE TITLE
DOCS: Default user/login password

### ISSUE THREAD

**Issue by lingrem** [clipos/bugs#23]
I successfully built OS and booted it, but cannot login =)
I did not find any information about default login and password of qemu image in documentation. I think it is a good idea to write it in the doc page or give a link to document with it. Could you share it please?

**Comment by travier-anssi** [comment]
Did you turn on instrumentation for `clipos/core`? Default builds are production builds with no login credentials allowed at the console. Please see the [last two sections of the `Building` page](https://docs.clip-os.org/toolkit/build.html#building-a-qemu-image-and-running-using-qemu-kvm) for steps to enable local password-less root login for development builds.

**Comment by travier-anssi** [comment]
Closing this issue as it has not received feedback in 4 weeks.
Feel free to reopen if you have additional information.

**Comment by magiitek** [comment]
Nice
