### ISSUE TITLE
Feature Request: Community chat room

### ISSUE THREAD

**Issue by ghost** [clipos/bugs#25]
I think clip-os could use a community chat.

I'm not sure if this (the bug tracker) is the right place - if not please let me know where I can post this and close this issue.

## Expected Behavior

I can join the community chat room and chat about clip-os awesomeness and problems.

## Actual Behavior

I'm stuck with the github issue tracker

## Steps to Reproduce the Problem

1. Search for clip-os community chatroom.
1. Only find the github issue tracker.

## Howto fix

I would like if we would not use slack or any other proprietary thingy for this. I would like to propose to do this in #clip-os on freenode (IRC). What do you guys think?

**Comment by tsautereau-anssi** [comment]
Hi Peter,

Our [Discourse](https://discuss.clip-os.org/) is meant for that.

**Comment by ghost** [comment]
Hm, thats a good thing to have.

But a chat would also be nice to have.. If this project will be qubes-sized at some point it would be lovely to "chat" with people instead of sticking to issues.

Sure you don't want IRC or (maybe even better) riot?

**Comment by Jaques-Menestre** [comment]
Hi the communauty is big now

**Comment by travier-anssi** [comment]
We currently have no plan to add real time communication channels but this may evolve in the future. As Thibaut said, please file issues for bugs here and start discussions on [Discourse](https://discuss.clip-os.org/). We generally answer quite quickly and the discussion will benefit everyone. If you wish to ask us private questions, please use emails for now.
