### ISSUE TITLE
Core: Support log forwarding via a Syslog-like protocol

### ISSUE THREAD

**Issue by travier-anssi** [clipos/bugs#27]
## Core changes
- [x] Choose between `rsyslog`, `syslog-ng`, etc. This choice should preferably be based on a factual comparison with security taken into account.
  - [x] Most major Linux distributions are using `rsyslog`.
- [x] Harden the daemon's systemd unit.
- [x] Harden the daemon's configuration.
- [x] Select which options may be changed at runtime by the system administrator.

## Testing infrastructure
- [x] Sample configuration for the QEMU test target.
- [x] Script to provision a remote test server.

**Comment by czanik** [comment]
Being syslog-ng evangelist, I can't help in choosing, as I'm strongly biased :-) But if you need help with syslog-ng, let me know.

**Comment by travier-anssi** [comment]
@czanik Thanks!
Do you have any pointers to audit reports, independent evaluation (including security or not) or even subjective comparison for syslog-ng?

**Comment by travier-anssi** [comment]
This has been completed successfully as of:
  * https://github.com/clipos/src_portage_clipos/commit/45f6a8ef984a8007ff24f4cc0bf8a7ac69558c31
  * https://github.com/clipos/products_clipos/commit/4dae1e1b84188c85237a65a0d0f5fedb7e5f444a
  * https://github.com/clipos/testbed/commit/124a4aac49e3a94690b8fcd18540bb963d10dca7
