### ISSUE TITLE
Quick try link to https://discuss.clip-os.org/t/nightly-builds-are-now-available/65 does not resolv to a web page.

### ISSUE THREAD

**Issue by EZAnonymous** [clipos/bugs#33]
## Expected Behavior
Click on "Quick Try" link should open page 
https://discuss.clip-os.org/t/nightly-builds-are-now-available/65

## Actual Behavior
but this link does not succeed to open.
This is a severe bug because the title "Quick Try" hints this is the easy way.
If this is the easy way, do you think other ways will be harder to follow (will I try something else before try to test another part of the website or of clip os if this basic initial step is corrupt)?
I want to warn you about the evaluation of Clip OS quality (it includes documentation quality); this bug leads to a 0 quality on a scale 0-10 because it shows to a new curious user that 
1) the web site have not been tested 
2) the user role of Clip OS have not been taken in consideration by the dev team (who will try an os when the first step for using it fails before any step started) 
3) testers professionals have not been hired in the project team (these kind of bug is the first any tester can find about a use case of a new evaluator can enter). 

## Steps to Reproduce the Problem

1. open in a web browser (firefox for instance) https://docs.clip-os.org/;
2. click on link "Quick Try";
3. wait for page to load (long time waiting until timeout).

## Specifications

- Version: https://docs.clip-os.org
- Platform: Any Debian GNU/Linux or Devuan fork from Debian
- Subsystem: firefox web browser 60.9.0esr

**Comment by tsautereau-anssi** [comment]
The link itself is correct, but [Discourse was facing a DDOS yesterday afternoon](https://twitter.com/discourse/status/1196808632320643073). The page you mention loads fine now.

Thanks for the report.

**Comment by EZAnonymous** [comment]
I acknowledge you do not consider this as a bug. Nevertheless, do you have a mirroring system like Debian allowing to continue service even when facing DDOS on central system?
Your answer shows your security policy for the front image you show to new users does not take in account the prejudice such DDOS attack can have on potential users.
Debian have taken this issue for more than a decade with a set of mirrors websites.
You are the front line of French security agency ANSSI: I really enjoy your initiative with Clip OS and I hope my message will help you to enhance to use the same strategy as Debian and to consider my bug report as showing an important issue not only about the doc website of clip-os.org but as a security concern that european web sites often encounter.
So the question I ask is : should ANSSI and other EU security services could propose to EU government web services a global european wide service of mirroring (not only for clip-os) that could prevent any DDOS atrack by the use of replication mirrors?
Thanks for listening and considering my small piece of stone to our community building.

**Comment by travier-anssi** [comment]
@EZAnonymous The public infrastructure available for CLIP OS development is just that: a development infrastructure. Any production deployment of CLIP OS can use its own, offline (thus impossible to DDOS) infrastructure. The documentation is available offline from the docs repository. The Discourse instance is backed up at regular intervals.
