### ISSUE TITLE
doc: CONFIG_X86_VSYSCALL_EMULATE option doesn't exist

### ISSUE THREAD

**Issue by a13xp0p0v** [clipos/bugs#35]
Hello!

The CLIP OS documentation about the kernel configuration has a mistake.
The `CONFIG_X86_VSYSCALL_EMULATION` option is called `CONFIG_X86_VSYSCALL_EMULATE` there: https://docs.clip-os.org/clipos/kernel.html#configuration

Could you please fix the name of this option? Thanks!

Best regards,
Alexander

**Comment by tsautereau-anssi** [comment]
Fixed, thanks @a13xp0p0v!
