### ISSUE TITLE
Documentation - Typo in SDK chapter

### ISSUE THREAD

**Issue by ptitoliv** [clipos/bugs#4]
There is a typo in the documentation at the following URL https://docs.clip-os.org/toolkit/build.html#activate-the-toolkit-environment in the chapter SDK

The command line written in the doc is 

`$ sujust products/clipos/sdk/bootstrap-from-sratch` in stead of 

`$ sujust products/clipos/sdk/bootstrap-from-scratch.`

Scratch is not well written.

**Comment by travier-anssi** [comment]
Thanks for the report. I'll push an update soon.

**Comment by travier-anssi** [comment]
Fixed by https://github.com/clipos/toolkit/commit/3cd2f0507da89f7a385cb8b33cae6c98f0577e09.

Thanks
