### ISSUE TITLE
[clipos4] need to try it

### ISSUE THREAD

**Issue by theLOICofFRANCE** [clipos/bugs#5]
Good morning, everyone,

I successfully tested the 5 alpha version, but I admit I was disappointed in the lack of the graphical environment presented at the [SSTIC 2015](https://www.sstic.org/2015/presentation/clip/).

Is it possible to provide us with an "unofficial and outdated" version of clipos 4, this version using linux-4.9.x-unofficial_grsec whose patches seem functional. This will allow people to easily test and better understand the work you have done.

If it is impossible to make a qemu or iso image available, will it be possible to create documentation to compile version 4?

I am grateful to you for the release of your sources. This request is not intended to bother you, it is just a request from someone very interested by this project. 

Thanks. Best regards,

## Specifications

- Version: clip-os 4 with linux-unofficial_grsec

**Comment by yaperez-anssi** [comment]
> I successfully tested the 5 alpha version, but I admit I was disappointed in the lack of the graphical environment presented at the [SSTIC 2015](https://www.sstic.org/2015/presentation/clip/).

Yes, as indicated in the announcement, version 5 is really preliminary and doesn't include any graphical component.
> 
> Is it possible to provide us with an "unofficial and outdated" version of clipos 4, this version using linux-4.9.x-unofficial_grsec whose patches seem functional. This will allow people to easily test and better understand the work you have done.

That's not something currently planned and it's quite unlikely to be done, for various reason including time constraints.
> 
> If it is impossible to make a qemu or iso image available, will it be possible to create documentation to compile version 4?

Again, that's not something we're currently interested in. CLIP OS 4 was never designed to be released to the public, so we tried to do the best we could. We know some people would have been interested in a complete release of a working project, but this would have delayed the release months and months and taken time better spent in building CLIP OS 5. More likely we would have never released anything.

I'm closing this request, as our current focus here is with CLIP OS 5, not CLIP OS 4.

**Comment by theLOICofFRANCE** [comment]
Hello @yaperez-anssi,

I just saw that @travier-anssi, @ptrebuchet-anssi & @msalaun-anssi is taking care of it:
https://discuss.clip-os.org/t/building-clip-os-v4-from-published-sources/49

Thanks !
