### ISSUE TITLE
Debian: Improve sujust alias command

### ISSUE THREAD

**Issue by ptitoliv** [clipos/bugs#6]
As told in the documentation it is needed to force the PATH of the local user in order to have the correct path when using sujust.

I was thinking it would be maybe better to do it only when using the sujust alias with such a command : 

` alias sujust='sudo -E --preserve-env=PATH env PATH=$PATH:/sbin:/usr/sbin just'`

Tested on a Debian sid with success.

**Comment by travier-anssi** [comment]
I think that's what are currently doing:
* https://github.com/clipos/toolkit/blob/master/source_me.sh#L228
* https://github.com/clipos/toolkit/blob/master/cosmk/__main__.py#L342

We need to change this part in the documentation.

Thanks.

**Comment by ptitoliv** [comment]
Actually, the current command in the source_me.sh didn't work on my Debian sid but I think it's because I didn't update my PATH variable as precised in the documentation. If i do an export PATH with /sbin:/usr/sbin, it works. 

My idea was to force /sbin and /usr/sbin in the sujust alias in order to avoid to update the user PATH variable. But it's indeed just a simple suggestion.

Thanks.

**Comment by travier-anssi** [comment]
Oh, sorry, I understand now. I had missed the part where you update the PATH. We will have a look at this as changing this alias turned up surprising results before.

**Comment by travier-anssi** [comment]
The cosmk toolkit has been rewritten in Go and do not rely anymore on root access (using rootless containers). Those changes are however still in review / testing (see [review.clip-os.org](https://review.clip-os.org/q/status:open)) but will be merged soon. Closing this issue as it will be resolved soon.
