### ISSUE TITLE
Debian SDK: Hardcoded rootfs path

### ISSUE THREAD

**Issue by ptitoliv** [clipos/bugs#7]
In the file products/clipos/sdk_debian/receipe.toml file, the rootfs file path is hardcoded with a generation date : 

`rootfs_archive = "{{repo}}/assets/debian/rootfs-2018-07-27.tar.xz"`

Then if the debian rootfs has been generated, the file path is different and it's impossible for the qemu/bundle target to find the rootfs : 

```
~/clipos$ ls assets/debian/
cache  rootfs-2018-10-07.tar.xz
```
```
~/clipos$ sujust products/clipos/qemu/bundle
just ../sdk_debian/all
 [X] Uncaught unknown exception FileNotFoundError:
     [Errno 2] No such file or directory: '/home/ptitoliv/clipos/assets/debian/rootfs-2018-07-27.tar.xz'
error: Recipe `bootstrap` failed with exit code 1
error: Recipe `sdk` failed on line 11 with exit code 1
```

Workaround is to change manually the root path in the receipe.toml file.

**Comment by travier-anssi** [comment]
This is by design, just like the Gentoo stage 3 rootfs path is hardcoded for the 'sdk' recipe.
When rebuilding the Debian rootfs, you should update the path in the 'sdk_debian' recipe.

**Comment by ptitoliv** [comment]
Hello @travier-anssi.

Ok I see. So I guess it's not a bug. However, maybe it would be interesting to describe it in the documentation ? Or maybe a code solution creating a symlink named rootfs linked to the last Debian rootfs built and using that symlink in the sdk_debian recipe ?

**Comment by travier-anssi** [comment]
I like the symlink idea. We are indeed still writing the documentation for recipes & products.

**Comment by ptitoliv** [comment]
Hello,

Just did a PR as a first test contribution about this issue : https://github.com/clipos/products_clipos/pull/1

**Comment by travier-anssi** [comment]
Thanks, we will take a look.

**Comment by travier-anssi** [comment]
Hi, we still working on improvement on this front (both in code and documentation). We will keep the current behavior for now.

**Comment by travier-anssi** [comment]
The Debian SDK has been removed for now. This issue is thus resolved. Thanks for the report.
